image: ruby:2.4
stages:
  - build
  - test
  - review
  - stage
  - production

services:
  - docker:dind

variables:
  DATABASE_URL: 'mongodb:///mongo/user_posts'
  DOCKER_DRIVER: overlay2
  LATEST_VERSION: 'insecuritystone/redditapp:latest'
  # LOCAL_REGISTRY: '35.210.68.182:5000'
  # USER_REG: 'user'
  # PASS_REG: 'pass'
  DOCKER_USER: 'insecuritystone'
before_script:
  - cd reddit
# - docker info
build_job:
  stage: build
  image: docker:stable
  ### need use $CI_SERVER_TLS_CA_FILE
  ### also re-create certificates for local registry
  script:
      - docker info
      - docker login -u $DOCKER_USER -p $DOCKER_SECRET
      - docker build -t $LATEST_VERSION .
      # - docker push $LOCAL_REGISTRY/$LATEST_VERSION && docker image rm $LATEST_VERSION
      - docker push $LATEST_VERSION && docker image rm $LATEST_VERSION

test_unit_job:
  image: $LATEST_VERSION
  stage: test
  services:
    - mongo:latest
  script:
    - ls
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy review'
  environment:
    name: dev
    url: http://dev.example.com

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'stage'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'PRODPRODPROD'
  environment:
    name: production
    url: https://example.com
