---
global:
  slack_api_url: 'https://hooks.slack.com/services/token/token/token'
  # global
  smtp_from: 'from_user@example.com'
  smtp_smarthost: 'smtp.example.com:587'
  smtp_auth_username: 'from_user'
  smtp_auth_password: 'password'

route:
  receiver: multi-notification

receivers:
- name: multi-notification
  slack_configs:
  - channel: '#stanislav_linnik'
  email_configs:
  - to: 'to_user(s)@example.com'
    # local
    from: 'from_user@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'from_user@example.com'
    auth_password: 'password'
    auth_secret: 'from_user@example.com'
    auth_identity: 'from_user@example.com'
