concurrent = 5
check_interval = 3

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker"
  url = "https://mygitlab.com/"
  token = "dq41jHEhKmUbDmuwmFW7"
  executor = "docker"
 [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    extra_hosts = ["mygitlab.com:35.210.68.182"]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
