{
 "title": "Docker telegraf",
 "time": { "from": "now-6h", "to": "now+15m" },
 "refresh": "10s",
 "panels": [
  {
   "title": "docker_container_cpu_usage_percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{container_name}}"
    },
    {}
   ]
  },
  {
   "title": "Disk space usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "disk_used_percent{path=\"/rootfs\"}"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\"}+cpu_usage_system{cpu=\"cpu-total\"}+cpu_usage_iowait{cpu=\"cpu-total\"}+cpu_usage_irq{cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(mem_total - mem_available) / mem_total * 100"
    },
    { "legendFormat": "Mb" }
   ]
  },
  {
   "title": "Swap usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "swap_used_percent" }
   ]
  },
  {
   "title": "Running containers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_n_containers_running", "legendFormat": "{{engine_host}}" }
   ]
  },
  {
   "title": "Container network receive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"^h.*\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container network transmit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"^h.*\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}