{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "http_server_request_duration_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "get status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{path=\"/\"}[1m]) or rate(ui_request_count{path=\"/new\",method=\"GET\"}[1m])"
    }
   ]
  },
  {
   "title": "Error http_status",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  }
 ]
}