groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    - alert: uiReqRespPercentile
      expr: histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le)) >= 0.045
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been grown above 0.045'
        summary: 'Oh no req/resp {{ $labels.instance }} growing above 0.045 on 95 percentile '
